#!/bin/bash
# Sample configuration script for projects that use savi_ros_bdi.

# Set the location of savi_ros_bdi here
SAVI_ROS_DIR=~/SAVI_ROS/rosjavaWorkspace/src/savi_ros_java/savi_ros_bdi

# Set the location of this project
PROJECT_DIR="$(pwd)"

# Configuration file path
CONFIG_FILE_NAME=/settings.cfg
CONFIG_PATH=$PROJECT_DIR$CONFIG_FILE_NAME

echo $SAVI_ROS_DIR
echo $CONFIG_PATH

#/build/instl/savi_ros_bdi/bin