#!/bin/bash
# Sample configuration script for projects that use savi_ros_bdi.

# Set the location of savi_ros_bdi here
SAVI_ROS_DIR=~/SAVI_ROS/rosjavaWorkspace/src/savi_ros_java/savi_ros_bdi/

# Set the location of this project
PROJECT_DIR="$(pwd)"

echo $SAVI_ROS_DIR
echo $PROJECT_DIR

#/build/instl/savi_ros_bdi/bin